### PR TITLE
Command/option/granularity

### PR DESCRIPTION
**Pull request by GoldenJoe**
This adds the option to specify granularity "-g" for generated reports, rather than relying on automatic calculation.

### CODE REVIEW

**Comment by scbray1** [comment]
Which version of Nmon Visualizer uses this ? Please provide an example of how to use this option on the command line.

**Comment by hpresnall** [comment]
This isn't in a release version yet but if you build a version yourself it will be there. Just add something like `-g 30` when running `ReportGenerator`.

**Comment by scbray1** [comment]
I see that the GUI has View -> Set Granularity but the command line won't accept the -g option. What is the default Granularity ?

**Comment by GoldenJoe** [comment]
Like scbray1 said, you have to compile it yourself to get the `-g` option. Default is automatic.

**Comment by scbray1** [comment]
It is not clear which values to use for granularity.
Please can you add something like the following to https://nmonvisualizer.github.io/nmonvisualizer/commandline.html :
    -g NNNNNN sets Granularity in seconds (or is it milliseconds).
        This will add data points to the charts every Granularity seconds.
    Min Granularity      =       1000
    Default Granularity  =      60000
    Max Granularity      = 2147475000 (max integer rounded down to nearest 15000)

**Comment by hpresnall** [comment]
So, it's supposed to be in seconds but I have a bug. Unless you want to build manually with the fix I just added, use milliseconds for now.

I've updated the docs to add more about this too.

**Pull request merged**
